name: Update
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:
jobs:
  update:
    name: update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Update
        run: |
         python movers.py
      - name: Commit
        run: |
          git config --global user.email "cajeros-bot@example.com"
          git config --global user.name "cajeros-bot"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "[ci] update"; git push -q "https://$GH_TOKEN@github.com/mauforonda/cajeros.git" main)
