name: Update
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:
jobs:
  update:
    name: update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Update
        run: |
          mkdir data
          python movers.py
      - name: Publish
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./data
          force_orphan: true
          user_name: cajeros-bot
          user_email: cajeros-bot@example.com